version: '3'
services:
  beets-flask-tests:
    container_name: beets-flask-tests
    hostname: beets-container
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        # 502 is default on macos, 1000 on linux
        USER_ID: 502
        GROUP_ID: 502
    image: beets-flask-tests
    ports:
      - "5001:5001"
      - "5173:5173"
    environment:
      LOG_LEVEL_SERVER: DEBUG # container console
      LOG_LEVEL_WEB: DEBUG # web interface console
      # inside the container
      LOG_FILE_WEB: "/repo/log/for_web.log"
    volumes:
      - ./:/repo/
