version: "3"
services:
    beets-flask:
        container_name: beets-flask
        hostname: beets-container
        build:
            context: .
            dockerfile: Dockerfile
            target: dev # or prod
            args:
                # 502 is default on macos, 1000 on linux
                USER_ID: 1000
                GROUP_ID: 1000
        image: beets-flask
        restart: unless-stopped
        ports:
            - "5001:5001" # production and backend
            - "5173:5173" # for vite dev server
        environment:
            LOG_LEVEL_BEETSFLASK: DEBUG  # this is used for our own logs. (set beets level via the config)
            LOG_LEVEL_OTHERS: WARNING # this is passed python logging basic config (all other modules)
        volumes:
            # beets puts its config files into the home directory
            # We dont use the home directory for anything else, so its easy to
            # make the configs persistent that way.
            # create these folders before starting the container! otherwise you get permission issues.
            - ${PWD}/local_data/user/:/home/beetle/
            # if you want to use the same beets-library inside and out,
            # you need to map your music folder in the container to the same path as outside
            # and make sure the config used in the container has the right path!
            - ${PWD}/local_data/music/:/music/
            # for development. (disable if target is `prod`)
            - ./:/repo/
