services:
  beets-flask-tests:
    container_name: beets-flask-tests
    hostname: beets-container
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        # 502 is default on macos, 1000 on linux
        USER_ID: 502
        GROUP_ID: 502
    image: beets-flask-tests
    ports:
      - "5001:5001"
      - "5173:5173"
    volumes:
      - ./:/repo/
