# minimal config that assumes that your music sits in `/music/imported`

gui:
    library:
        include_paths: yes
        readonly: yes
        jsonify_prettyprint_regular: no

    tags:
        recent_days: 14 # Number of days to consider for the "recent" tag group

    inbox:
        # keep in mind to volume-map these folders in your docker-compose.yml
        folders:
        - "inbox" : '/music/inbox'


directory: /music/imported
# library: /home/user/.config/beets/library.db # default location

import:
    # for our gui it makes sense to keep files around (copy) and
    # only clear occasionally by hand (we have a button for that)
    move: no
    copy: yes
    write: yes
    log: /music/last_beets_imports.log
    quiet_fallback: skip
    detail: yes # `yes` is needed for our previews to work.

ui:
    color: yes

replace:
    '[\\]':         ''
    '[_]':          '-'
    '[/]':          '-'
    '^\.+':         ''
    '[\x00-\x1f]':  ''
    '[<>:"\?\*\|]': ''
    '\.$':          ''
    '\s+$':         ''
    '^\s+':         ''
    '^-':           ''
    '’':            ''
    '′':            ''
    '″':            ''
    '‐':            '-'

threaded: yes
asciify_paths: yes
