# minimal config that assumes that your music sits in `/music/imported`

gui:
    num_workers_preview: 4 # how many previews to generate in parallel

    library:
        readonly: no
        include_paths: yes

    tags:
        expand_tags: yes # for tag groups, on page load, show tag details?
        recent_days: 14 # Number of days to consider for the "recent" tag group

    terminal:
        start_path: "/music/inbox" # the directory where to start new terminal sessions

    inbox:
        concat_nested_folders: yes # show multiple folders in one line if they only have one child
        expand_files: no # on page load, show files in (album) folders, or collapse them
        order_by: "name" # how to sort tags within the trag groups: "name" (the album folder basename) | "date_created" | "date_modified"

        folders: # keep in mind to volume-map these folders in your docker-compose.yml
            Inbox:
                name: "Inbox"
                path: "/music/inbox"
                autotag: no # no | "preview" | "import"

directory: /music/imported
# library: /home/user/.config/beets/library.db # default location

import:
    # for our gui it makes sense to keep files around (copy) and
    # only clear occasionally by hand (we have a button for that)
    move: no
    copy: yes
    write: yes
    log: /music/last_beets_imports.log
    quiet_fallback: skip
    detail: yes # `yes` is needed for our previews to work.
    duplicate_action: ask # ask|skip|merge|keep|remove

ui:
    color: yes

replace:
    '[\\]': ""
    "[_]": "-"
    "[/]": "-"
    '^\.+': ""
    '[\x00-\x1f]': ""
    '[<>:"\?\*\|]': ""
    '\.$': ""
    '\s+$': ""
    '^\s+': ""
    "^-": ""
    "’": ""
    "′": ""
    "″": ""
    "‐": "-"

threaded: yes
asciify_paths: yes
